version: "3.7"
services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks: 
      mynet:
        ipv4_address: 10.5.0.5
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  cassandra:
    image: "cassandra"
    container_name: cassandra
    hostname: cassandra
    networks: 
      mynet:
        ipv4_address: 10.5.0.7
    ports:
      - 9042:9042
    volumes:
      - d:/Dev/Local-Dockers/cassandra-data:/var/lib/cassandra 
      
  redis:
    image: "redis"
    container_name: redis
    hostname: redis
    networks: 
      mynet:
        ipv4_address: 10.5.0.9
    ports:
      - 6379
networks:
  mynet:
    external: true
    name: docker-spark_spark-network