version: "3.7"
services:
  api:
    image: bling-api:latest
    container_name: bling-api
    hostname: bling-api
    ports:
      - 37600:37600
    networks:
      - mynet
networks:
  mynet:
    external: true
    name: ${NETWORK_NAME}