version: "3.7"
services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks: 
      - mynet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
      
  redis:
    image: "redis"
    container_name: redis
    hostname: redis
    networks: 
      - mynet
    ports:
      - 32769:6379
networks:
  mynet:
    external: true
    name: ${NETWORK_NAME}