version: "3.7"
services:
  spark-master:
    image: spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      mynet:
        ipv4_address: 10.5.0.2
    volumes:
       - ./bling_eng_jar:/opt/spark-apps
       - ./spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "4040:4040"
    env_file: ./spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      mynet:
        ipv4_address: 10.5.0.3
    volumes:
       - ./bling_eng_jar:/opt/spark-apps
       - ./spark-data:/opt/spark-data
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
      - "4041:4040"
    env_file: ./spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      mynet:
        ipv4_address: 10.5.0.4
    volumes:
       - ./bling_eng_jar:/opt/spark-apps
       - ./spark-data:/opt/spark-data
networks:
  mynet:
    external: true
    name: docker-spark_spark-network